org.gradle.jvmargs=-Xmx4096m --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED
org.gradle.java.home=C:\jdk-25.0.1+8
org.gradle.parallel=true
org.gradle.caching=true