/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package xyz.kyngs.librelogin.common.config;

import xyz.kyngs.librelogin.common.config.key.ConfigurationKey;

/**
 * All the keys for the messages
 * BTW: Most of the comments were generated by GitHub's Copilot :D
 */
@SuppressWarnings("unused")
public class MessageKeys {

    /*
    Kicks related to autologin
     */

    public static final ConfigurationKey<String> KICK_PREMIUM_ERROR_THROTTLED = new ConfigurationKey<>(
            "kick-premium-error-throttled",
            "The Mojang API is rate limiting our server, please try joining again in a while!",
            "This message is displayed when the Mojang API is rate limiting us, therefore we cannot verify whether there is an account with the given username.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> KICK_PREMIUM_ERROR_UNDEFINED = new ConfigurationKey<>(
            "kick-premium-error-undefined",
            "There was some issue while communicating with Mojang, if the problem persists, contact the server administrators!",
            """
                    This message is displayed when there was an unknown issue while communicating with Mojang, therefore we cannot verify whether there is an account with the given username.
                    The error will be printed to the console""",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> KICK_PREMIUM_INFO_ENABLED = new ConfigurationKey<>(
            "kick-premium-info-enabled",
            "Autologin enabled!",
            "This message is displayed when the player enables autologin, they need to be kicked.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> KICK_PREMIUM_INFO_DISABLED = new ConfigurationKey<>(
            "kick-premium-info-disabled",
            "Autologin disabled!",
            "This message is displayed when the player disables autologin, they need to be kicked.",
            ConfigurateHelper::getString
    );

    /*
    Kicks related to username
     */

    public static final ConfigurationKey<String> KICK_INVALID_CASE_USERNAME = new ConfigurationKey<>(
            "kick-invalid-case-username",
            "Please, change your username to &c%username%",
            """
                    This message is displayed when the player's username is not in the correct case.
                    See https://github.com/kyngs/LibreLogin/wiki/Name-Validation for more information.""",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> KICK_OCCUPIED_USERNAME = new ConfigurationKey<>(
            "kick-occupied-username",
            "Please, change your username to &c%username%",
            """
                    This message is displayed when the player's username is already taken.""",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> KICK_ILLEGAL_USERNAME = new ConfigurationKey<>(
            "kick-illegal-username",
            "You have illegal characters in your username or/and your username is longer than 16 characters!",
            """
                    This message is displayed when the player's username is not allowed.
                    See https://github.com/kyngs/LibreLogin/wiki/Name-Validation for more information.""",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> KICK_NAME_MISMATCH = new ConfigurationKey<>(
            "kick-name-mismatch",
            "Oh no! It looks like an premium user with activated auto login changed their nickname to %nickname%, therefore there are 2 colliding accounts. Please contact support immediately.",
            """
                    This occurs, when there is a profile conflict.
                    See https://github.com/kyngs/LibreLogin/wiki/Profile-Conflicts for more information.""",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> KICK_SHORT_USERNAME = new ConfigurationKey<>(
            "kick-short-username",
            "Your username is too short! The minimum length is %length% letters.",
            """
                    This message is displayed when the player's username is too short.
                    See the configuration key "minimum-username-length" for more information.""",
            ConfigurateHelper::getString
    );

    /*
    Other kicks
     */

    public static final ConfigurationKey<String> KICK_IP_LIMIT = new ConfigurationKey<>(
            "kick-ip-limit",
            "You have reached the maximum amount of accounts per IP!",
            """
                    This message is displayed when the player's IP has reached the maximum amount of accounts.
                    See the configuration key "ip-limit" for more information.""",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> KICK_NO_LOBBY = new ConfigurationKey<>(
            "kick-no-lobby",
            "There's no available lobby to connect you to. Please try again later.",
            "This message is displayed when the player is kicked because there is not any server available.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> KICK_NO_LIMBO = new ConfigurationKey<>(
            "kick-no-limbo",
            "There's no available limbo to connect you to. Please try again later. If you're the server administrator, please install NanoLimboPlugin.",
            "This message is displayed when the player is kicked because there is not any limbo available.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> KICK_TIME_LIMIT = new ConfigurationKey<>(
            "kick-time-limit",
            "You took too long to authorize!",
            "This message is displayed when the player takes too long to authorize. (You can specify this time limit in the config file)",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> KICK_ERROR_PASSWORD_WRONG = new ConfigurationKey<>(
            "kick-error-password-wrong",
            "Wrong password!",
            "This message is displayed when the player is kicked because they authorize with wrong password.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> KICK_2FA_ENABLED = new ConfigurationKey<>(
            "kick-2fa-enabled",
            "Two-factor has been enabled! Please reconnect.",
            "This message is displayed when the player enables 2FA.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> KICK_ALREADY_CONNECTED = new ConfigurationKey<>(
            "kick-already-connected",
            "You are already connected!",
            "This message is displayed when the player is already connected, but tries to join from another location.",
            ConfigurateHelper::getString
    );

    /*
    Errors related to commands
     */

    public static final ConfigurationKey<String> ERROR_FROM_FLOODGATE = new ConfigurationKey<>(
            "error-from-floodgate",
            "You can't use this command from Floodgate!",
            "This message is displayed when the player is executing a command, but they are coming from Floodgate.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_NO_EMAIL = new ConfigurationKey<>(
            "error-no-email",
            "You don't have a recovery email set!",
            "This message is displayed when the player tries to recover their password, but they don't have a recovery email set.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_ALREADY_AUTHORIZED = new ConfigurationKey<>(
            "error-already-authorized",
            "You are already authorized!",
            "This message is displayed when the player tries to authorize again.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_ALREADY_REGISTERED = new ConfigurationKey<>(
            "error-already-registered",
            "You are already registered!",
            "This message is displayed when the player tries to register again.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_NOT_AUTHORIZED = new ConfigurationKey<>(
            "error-not-authorized",
            "Please authorize first!",
            "This message is displayed when the player tries to use a command that requires authorization.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_NOT_REGISTERED = new ConfigurationKey<>(
            "error-not-registered",
            "Please register first!",
            "This message is displayed when the player tries to login, when they are not registered.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_NOT_PAID = new ConfigurationKey<>(
            "error-not-paid",
            "This account does not exist in the Mojang database!",
            "This message is displayed when the player tries to enable autologin, but their account does not exist in the Mojang database.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_NOT_PREMIUM = new ConfigurationKey<>(
            "error-not-premium",
            "You do not have autologin enabled, enable it using /premium <password>!",
            "This message is displayed when the player tries to disable autologin, but they do not have it enabled.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_NOT_CRACKED = new ConfigurationKey<>(
            "error-not-cracked",
            "You have autologin enabled, disable it using /cracked!",
            "This message is displayed when the player tries to enable autologin, but they already have it enabled.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_PASSWORD_WRONG = new ConfigurationKey<>(
            "error-password-wrong",
            "Wrong password!",
            "This message is displayed when the player tries to authorize with wrong password.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_NO_PASSWORD = new ConfigurationKey<>(
            "error-no-password",
            "You don't have a password. You can try using /cracked to disable autologin, and then register.",
            "This message is displayed when the player tries to change password without having one.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> TOTP_NOT_PROVIDED = new ConfigurationKey<>(
            "totp-not-provided",
            "You must provide a 2FA code! Use /login <password> <2FA code>, if you lost your code, contact the admins.",
            "This message is displayed when the player tries to authorize without providing a 2FA code.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> TOTP_WRONG = new ConfigurationKey<>(
            "totp-wrong",
            "Wrong 2FA code!",
            "This message is displayed when the player tries to authorize, or finish the 2FA enablement, with a wrong 2FA code.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> TOTP_NOT_AWAITING = new ConfigurationKey<>(
            "totp-not-awaiting",
            "You are currently not in the process of enabling 2FA! Please type /2fa to begin the process.",
            "This message is displayed when the player attempts to finish the 2FA process, but they are not in the process of enabling 2FA.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_PASSWORD_NOT_MATCH = new ConfigurationKey<>(
            "error-password-not-match",
            "Passwords do not match!",
            "This message is displayed when the player tries to register with different passwords.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_PASSWORD_TOO_SHORT = new ConfigurationKey<>(
            "error-password-too-short",
            "The password is too short! Minimum length is %length% characters.",
            "This message is displayed when the player tries to register with a password that is too short.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_FORBIDDEN_PASSWORD = new ConfigurationKey<>(
            "error-forbidden-password",
            "The password is not allowed! Please choose a different password.",
            "This message is displayed when the player tries to register with a forbidden (weak) password.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_PASSWORD_TOO_LONG = new ConfigurationKey<>(
            "error-password-too-long",
            "The password is too long!",
            "This message is displayed when the player tries to register with a password that is too long.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_PASSWORD_CORRUPTED = new ConfigurationKey<>(
            "error-password-corrupted",
            "Your password is corrupted, please contact an administrator!",
            "This message is displayed when the player tries to login with corrupted password.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_PREMIUM_THROTTLED = new ConfigurationKey<>(
            "error-premium-throttled",
            "The Mojang API is rate limiting our server, please try the command again in a while!",
            "This message is displayed when the Mojang API is rate limiting us, therefore we cannot verify whether there is an account with the given username.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_PREMIUM_UNKNOWN = new ConfigurationKey<>(
            "error-premium-unknown",
            "There was an unknown error while communicating with the mojang API, please check console for further details!",
            """
                    This message is displayed when there was an unknown issue while communicating with Mojang, therefore we cannot verify whether there is an account with the given username.
                    The error will be printed to the console""",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_THROTTLE = new ConfigurationKey<>(
            "error-throttle",
            "You are sending commands too fast! Please wait a bit.",
            "This message is displayed when the player tries to send commands too fast.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_NO_CONFIRM = new ConfigurationKey<>(
            "error-no-confirm",
            "Please use /premium <password> first!",
            "This message is displayed when the player tries to run /premiumconfirm, before running /premium.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_NO_MAIL_CONFIRM = new ConfigurationKey<>(
            "error-no-mail-confirm",
            "Please use /setemail <email> <password> first!",
            "This message is displayed when the player tries to run /mailconfirm, before running /mail.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_NO_PASSWORD_RESET = new ConfigurationKey<>(
            "error-no-password-reset",
            "Please use /resetpassword first!",
            "This message is displayed when the player tries to run /resetpasswordconfirm, before running /resetpassword.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_MAIL_THROTTLE = new ConfigurationKey<>(
            "error-mail-throttle",
            "You are sending emails too fast! Please wait a bit.",
            "This message is displayed when the player tries to send mail too fast.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_WRONG_MAIL_VERIFY = new ConfigurationKey<>(
            "error-wrong-mail-verify",
            "Wrong verification code!",
            "This message is displayed when the player tries to verify their email with a wrong verification code.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_WRONG_PASSWORD_RESET = new ConfigurationKey<>(
            "error-wrong-password-reset",
            "Wrong password reset code!",
            "This message is displayed when the player tries to reset their password with a wrong password reset code.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_CORRUPTED_MESSAGES = new ConfigurationKey<>(
            "error-corrupted-messages",
            "Messages are corrupted, old ones are going to be kept. Cause: %cause%",
            "This message is displayed when the messages.conf file is corrupted.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_CORRUPTED_CONFIGURATION = new ConfigurationKey<>(
            "error-corrupted-configuration",
            "Configuration is corrupted, old one is going to be kept. Cause: %cause%",
            "This message is displayed when the configuration file is corrupted.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_UNKNOWN = new ConfigurationKey<>(
            "error-unknown",
            "An unknown error occurred! Check console for further information.",
            "This message is displayed when an unknown error occurs.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_UNKNOWN_USER = new ConfigurationKey<>(
            "error-unknown-user",
            "This user does not exist!",
            "This message is displayed when someone attempts to refer an unknown user.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_OCCUPIED_USER = new ConfigurationKey<>(
            "error-occupied-user",
            "This username is already occupied!",
            "This message is displayed when someone tries to move account to an occupied username.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_PLAYER_ONLINE = new ConfigurationKey<>(
            "error-player-online",
            "This player is online!",
            "This message is displayed when someone attempts to refer an online player.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_PLAYER_OFFLINE = new ConfigurationKey<>(
            "error-player-offline",
            "This player is offline!",
            "This message is displayed when someone attempts to refer an offline player.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_PLAYER_AUTHORIZED = new ConfigurationKey<>(
            "error-player-authorized",
            "This player is already authenticated!",
            "This message is displayed when someone attempts to refer an authenticated player.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_PLAYER_NOT_REGISTERED = new ConfigurationKey<>(
            "error-player-not-registered",
            "This player is not registered!",
            "This message is displayed when someone attempts to refer an unregistered player.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_NOT_AVAILABLE_ON_MULTI_PROXY = new ConfigurationKey<>(
            "error-not-available-on-multi-proxy",
            "This feature is not available on MultiProxy!",
            "This message is displayed when someone attempts to use a feature that is not available on MultiProxy.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_PASSWORD_RESETTING_DISABLED = new ConfigurationKey<>(
            "error-password-resetting-disabled",
            "Password resetting is disabled!",
            "This message is displayed when someone attempts to reset password while it is disabled.",
            ConfigurateHelper::getString
    );

    /*
    ACF Related errors
     */

    public static final ConfigurationKey<String> ERROR_NO_PERMISSION = new ConfigurationKey<>(
            "error-no-permission",
            "You do not have permission to use this command!",
            "This message is displayed when the player does not have permission to use a command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_INVALID_SYNTAX = new ConfigurationKey<>(
            "error-invalid-syntax",
            "Usage: <c2>{command}</c2> <c3>{syntax}</c3>",
            "This message is displayed when the player uses a command with invalid syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_UNKNOWN_COMMAND = new ConfigurationKey<>(
            "error-unknown-command",
            "Unknown command!",
            "This message is displayed when the player uses an unknown command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_MAIL_NOT_SENT = new ConfigurationKey<>(
            "error-mail-not-sent",
            "Failed to send email, perhaps you typed your address wrong? If you are sure that you typed it correctly, please contact an administrator.",
            "This message is displayed when the player tries to send a mail, but it fails to send.",
            ConfigurateHelper::getString
    );

    /*
    General information messages
     */

    public static final ConfigurationKey<String> INFO_KICK = new ConfigurationKey<>(
            "info-kick",
            "You have been kicked from the server for the following reason: %reason%",
            "This message is displayed when the player is kicked from a server.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_LOGGING_IN = new ConfigurationKey<>(
            "info-logging-in",
            "Logging in...",
            "This message is displayed when the player attempts to log in.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_LOGGED_IN = new ConfigurationKey<>(
            "info-logged-in",
            "Logged in!",
            "This message is displayed when the player logs in.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_PREMIUM_LOGGED_IN = new ConfigurationKey<>(
            "info-premium-logged-in",
            "You have been logged in automatically!",
            "This message is displayed when the player logs in automatically because they have enabled /premium.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_SESSION_LOGGED_IN = new ConfigurationKey<>(
            "info-session-logged-in",
            "You have been logged in automatically!",
            "This message is displayed when the player logs in automatically because of a valid session.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_REGISTERING = new ConfigurationKey<>(
            "info-registering",
            "Registering...",
            "This message is displayed when the player attempts to register.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_REGISTERED = new ConfigurationKey<>(
            "info-registered",
            "Registered!",
            "This message is displayed when the player registers.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_ENABLING = new ConfigurationKey<>(
            "info-enabling",
            "Enabling...",
            "This message is displayed when something is enabling.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_DISABLING = new ConfigurationKey<>(
            "info-disabling",
            "Disabling...",
            "This message is displayed when something is disabling.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_EDITING = new ConfigurationKey<>(
            "info-editing",
            "Editing...",
            "This message is displayed when something is being edited.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_EDITED = new ConfigurationKey<>(
            "info-edited",
            "Edited!",
            "This message is displayed when something has been edited.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_RESETTING_PASSWORD = new ConfigurationKey<>(
            "info-resetting-password",
            "Resetting password...",
            "This message is displayed when the player attempts to reset their password.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_PASSWORD_RESET = new ConfigurationKey<>(
            "info-password-reset",
            "Password reset! You can now log in with your new password.",
            "This message is displayed when the player resets their password.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_DUMPING = new ConfigurationKey<>(
            "info-dumping",
            "Creating dump...",
            "This message is displayed when a user executes /librelogin dump.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_DUMPED = new ConfigurationKey<>(
            "info-dumped",
            "Dump saved to %file%!",
            "This message is displayed when a user executes /librelogin dump.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_DELETING = new ConfigurationKey<>(
            "info-deleting",
            "Deleting...",
            "This message is displayed when something is being deleted.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_DELETED = new ConfigurationKey<>(
            "info-deleted",
            "Deleted!",
            "This message is displayed when something has been deleted.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_RELOADING = new ConfigurationKey<>(
            "info-reloading",
            "Reloading...",
            "This message is displayed when something is being reloaded.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_RELOADED = new ConfigurationKey<>(
            "info-reloaded",
            "Reloaded!",
            "This message is displayed when something has been reloaded.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_SENDING_EMAIL = new ConfigurationKey<>(
            "info-sending-email",
            "Sending email...",
            "This message is displayed when the user executes a command that sends an email.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_SENT_EMAIL = new ConfigurationKey<>(
            "info-sent-email",
            "Email sent!",
            "This message is displayed when the user executes a command that sends an email.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_USER = new ConfigurationKey<>(
            "info-user",
            """
                    UUID: %uuid%
                    Premium UUID: %premium_uuid%
                    Last Seen: %last_seen%
                    Joined: %joined%
                    2FA: %2fa%
                    EMail: %email%
                    IP: %ip%
                    Last Authenticated: %last_authenticated%""",
            "This message is displayed when the player's information is requested.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_ABOUT = new ConfigurationKey<>(
            "info-about",
            """
                    This server is running FOSS authentication plugin, LibreLogin.
                    Version: %version%
                    Authors: kyngs, and other contributors
                    Source: https://github.com/kyngs/LibreLogin
                    License: Mozilla Public License 2.0""",
            """
                    This message is displayed when the player executes /librelogin about.
                    !! Clearing this message, or somehow making the command unexecutable is not only cringe, but also considered a violation of the license. !!""",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_NO_ALTS = new ConfigurationKey<>(
            "info-no-alts",
            "There are no other players with the same IP address.",
            "This message is displayed when the player has no alts.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_ALTS = new ConfigurationKey<>(
            "info-alts",
            "There are %count% players with the same IP address:",
            "This message is displayed when the player has alts.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_ALTS_ENTRY = new ConfigurationKey<>(
            "info-alts-entry",
            "- %name% (last seen: %last_seen%)",
            "This message is displayed when the player has alts.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_MAIL_SENDING = new ConfigurationKey<>(
            "info-mail-sending",
            "Sending email...",
            "This message is displayed when the user executes a command that sends an email.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_MAIL_VERIFIED = new ConfigurationKey<>(
            "info-mail-verified",
            "Email verified! You can now reset your password if you forget it.",
            "This message is displayed when the user verifies their email.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_VERIFICATION_MAIL_SENT = new ConfigurationKey<>(
            "info-verification-mail-sent",
            "Verification email sent! If you don't see anything in your inbox, check your spam folder. You have 10 minutes to verify your email.",
            "This message is displayed when the user executes a command that sends a verification email.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_RESET_PASSWORD_MAIL_SENT = new ConfigurationKey<>(
            "info-reset-password-mail-sent",
            "密码重置邮件已发送！如果您没有在收件箱中看到邮件，请检查垃圾邮件文件夹。您有 10 分钟的时间来重置密码。",
            "This message is displayed when the user executes a command that sends a reset email.",
            ConfigurateHelper::getString
    );

    /*
    Prompts
     */

    public static final ConfigurationKey<String> PROMPT_REGISTER = new ConfigurationKey<>(
            "prompt-register",
            "Please register using: &e/register &b<password> <password>",
            "This message is displayed when the player is prompted to register.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> PROMPT_LOGIN = new ConfigurationKey<>(
            "prompt-login",
            "Please login using: &e/login &b<password> [2fa_code]",
            "This message is displayed when the player is prompted to login.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> PROMPT_CONFIRM = new ConfigurationKey<>(
            "prompt-confirm",
            "You are about to enable premium autologin, please take note, that you &4WILL NOT&r be able to connect to your account from cracked client. You can turn this off later by using /cracked. To confirm this action, you have 5 minutes to run /confirmpremium",
            "This message is displayed when the player is prompted to confirm autologin.",
            ConfigurateHelper::getString
    );

    /*
    Titles
     */

    public static final ConfigurationKey<String> TITLE_REGISTER = new ConfigurationKey<>(
            "title-register",
            "&6&lRegister",
            "This title is displayed when the player is prompted to register. Make sure that you have use-titles set to true in the configuration.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> TITLE_LOGIN = new ConfigurationKey<>(
            "title-login",
            "&6&lLogin",
            "This title is displayed when the player is prompted to login. Make sure that you have use-titles set to true in the configuration.",
            ConfigurateHelper::getString
    );

    /*
    Subtitles
     */

    public static final ConfigurationKey<String> SUB_TITLE_REGISTER = new ConfigurationKey<>(
            "sub-title-register",
            "&e/register &b<password> <password>",
            "This subtitle is displayed when the player is prompted to register. Make sure that you have use-titles set to true in the configuration.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SUB_TITLE_LOGIN = new ConfigurationKey<>(
            "sub-title-login",
            "&e/login &b<password>",
            "This subtitle is displayed when the player is prompted to login. Make sure that you have use-titles set to true in the configuration.",
            ConfigurateHelper::getString
    );

    /*
    Actionbar
     */

    public static final ConfigurationKey<String> ACTION_BAR_REGISTER = new ConfigurationKey<>(
            "action-bar-register",
            "&e/register &b<password> <password>",
            "This actionbar is displayed when the player is prompted to register. Make sure that you have use-action-bar set to true in the configuration.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ACTION_BAR_LOGIN = new ConfigurationKey<>(
            "action-bar-login",
            "&e/login &b<password>",
            "This actionbar is displayed when the player is prompted to login. Make sure that you have use-action-bar set to true in the configuration.",
            ConfigurateHelper::getString
    );

    /*
    TOTP
     */

    public static final ConfigurationKey<String> TOTP_SHOW_INFO = new ConfigurationKey<>(
            "totp-show-info",
            """
                    Please scan the QR code on the map into your 2FA app. For example, Google Authenticator or Authy.
                    When you are complete, please execute the /2faconfirm <code> command to finish the process.
                    Disconnect to abort.""",
            "This message is displayed when the player is prompted to scan the 2FA QR code.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> TOTP_GENERATING = new ConfigurationKey<>(
            "totp-generating",
            "Generating 2FA code...",
            "This message is displayed when player has begun the 2FA enable procedure.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> TOTP_WRONG_VERSION = new ConfigurationKey<>(
            "totp-wrong-version",
            "You must connect with client version %low% - %high%, in order to enable 2FA. You can then connect back with old version again.",
            "This message is displayed when the player attempts to enable 2FA with an old client.",
            ConfigurateHelper::getString
    );

    /*
    Emails
     */

    public static final ConfigurationKey<String> EMAIL_VERIFICATION_CONTENT = new ConfigurationKey<>(
            "email-verification-content",
            """
                    Hello %name%!<br>
                    You have requested to add a recovery email on %server%.<br>
                    If you did not request this, please ignore this email.<br>
                    To confirm this action, please <b>run the following command in-game: </b><br>
                    <b><code><h1>/verifyemail %code%</h1></code></b><br>
                    """,
            "This email is sent to the player when they request to add a recovery email. You can insert any HTML code into this message.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> EMAIL_VERIFICATION_SUBJECT = new ConfigurationKey<>(
            "email-verification-subject",
            "Verify your email on %server%",
            "This is the subject of the email sent to the player when they request to add a recovery email.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> EMAIL_PASSWORD_RESET_CONTENT = new ConfigurationKey<>(
            "email-password-reset-content",
            """
                    Hello %name%!<br>
                    You (from IP %ip%) have requested to reset your password on %server%.<br>
                    If you did not request this, please ignore this email.<br>
                    To confirm this action, please <b>run the following command in-game: </b><br>
                    <b><code><h1>/confirmpasswordreset %code%</h1></code></b><br>
                    """,
            "This email is sent to the player when they request to reset their password. You can insert any HTML code into this message.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> EMAIL_PASSWORD_RESET_SUBJECT = new ConfigurationKey<>(
            "email-password-reset-subject",
            "Reset your password on %server%",
            "This is the subject of the email sent to the player when they request to reset their password.",
            ConfigurateHelper::getString
    );

    /*
    Commands Syntax
     */

    public static final ConfigurationKey<?> SYNTAX = ConfigurationKey.getComment(
            "syntax",
            "This section contains syntax for commands. It is pretty large, so most people leave the defaults."
    );

    public static final ConfigurationKey<String> SYNTAX_LOGIN = new ConfigurationKey<>(
            "syntax.login",
            "<password> [2fa_code]",
            "This message is displayed when the player attempts to login with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_REGISTER = new ConfigurationKey<>(
            "syntax.register",
            "<password> <passwordRepeat>",
            "This message is displayed when the player attempts to register with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_PREMIUM = new ConfigurationKey<>(
            "syntax.premium",
            "<password>",
            "This message is displayed when the player attempts to enable premium autologin with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_USER_INFO = new ConfigurationKey<>(
            "syntax.user-info",
            "<name>",
            "This message is displayed when the player attempts to get user info with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_USER_MIGRATE = new ConfigurationKey<>(
            "syntax.user-migrate",
            "<name> <newName>",
            "This message is displayed when the player attempts to migrate user with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_USER_UNREGISTER = new ConfigurationKey<>(
            "syntax.user-unregister",
            "<name>",
            "This message is displayed when the player attempts to unregister user with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_USER_DELETE = new ConfigurationKey<>(
            "syntax.user-delete",
            "<name>",
            "This message is displayed when the player attempts to delete user with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_USER_PREMIUM = new ConfigurationKey<>(
            "syntax.user-premium",
            "<name>",
            "This message is displayed when the player attempts to enable premium autologin for other user with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_USER_CRACKED = new ConfigurationKey<>(
            "syntax.user-cracked",
            "<name>",
            "This message is displayed when the player attempts to disable premium autologin for other user with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_USER_REGISTER = new ConfigurationKey<>(
            "syntax.user-register",
            "<name> <password>",
            "This message is displayed when the player attempts to register other user with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_USER_LOGIN = new ConfigurationKey<>(
            "syntax.user-login",
            "<name>",
            "This message is displayed when the player attempts to login other user with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_USER_2FA_OFF = new ConfigurationKey<>(
            "syntax.user-2fa-off",
            "<name>",
            "This message is displayed when the player attempts to disable 2FA for other user with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_USER_EMAIL_OFF = new ConfigurationKey<>(
            "syntax.user-email-off",
            "<name>",
            "This message is displayed when the player attempts to disable EMail for other user with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_USER_SET_EMAIL = new ConfigurationKey<>(
            "syntax.user-set-email",
            "<name> <email>",
            "This message is displayed when the player attempts to set EMail for other user with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_USER_ALTS = new ConfigurationKey<>(
            "syntax.user-alts",
            "<name>",
            "This message is displayed when the player attempts to get alts of other user with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_USER_CHANGE_PASSWORD = new ConfigurationKey<>(
            "syntax.user-pass-change",
            "<name> <newPassword>",
            "This message is displayed when the player attempts to change password for other user with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_2FA_CONFIRM = new ConfigurationKey<>(
            "syntax.2fa-confirm",
            "<code>",
            "This message is displayed when the player attempts to confirm 2FA with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_CHANGE_PASSWORD = new ConfigurationKey<>(
            "syntax.change-password",
            "<oldPassword> <newPassword>",
            "This message is displayed when the player attempts to change password with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_EMAIL_TEST = new ConfigurationKey<>(
            "syntax.email-test",
            "<address>",
            "This message is displayed when the player attempts to test email with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_SET_EMAIL = new ConfigurationKey<>(
            "syntax.set-email",
            "<address> <password>",
            "This message is displayed when the player attempts to set email with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_VERIFY_EMAIL = new ConfigurationKey<>(
            "syntax.verify-email",
            "<code>",
            "This message is displayed when the player attempts to verify email with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_RESET_PASSWORD = new ConfigurationKey<>(
            "syntax.reset-password",
            "",
            "This message is displayed when the player attempts to reset password with wrong syntax.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SYNTAX_CONFIRM_PASSWORD_RESET = new ConfigurationKey<>(
            "syntax.confirm-password-reset",
            "<code> <password> <passwordRepeat>",
            "This message is displayed when the player attempts to confirm password reset with wrong syntax.",
            ConfigurateHelper::getString
    );

    /*
    Commands autocomplete
     */

    public static final ConfigurationKey<?> AUTOCOMPLETE = ConfigurationKey.getComment(
            "autocomplete",
            """
                    This section contains autocompletes for commands. It is pretty large, so most people leave the defaults.
                    !!DO NOT TRANSLATE @players!! It is used to hint out all players online.
                    """
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_LOGIN = new ConfigurationKey<>(
            "autocomplete.login",
            "password",
            "This hint is displayed when the player starts typing the /login command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_REGISTER = new ConfigurationKey<>(
            "autocomplete.register",
            "password password",
            "This hint is displayed when the player starts typing the /register command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_PREMIUM = new ConfigurationKey<>(
            "autocomplete.premium",
            "password",
            "This hint is displayed when the player starts typing the /premium command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_USER_INFO = new ConfigurationKey<>(
            "autocomplete.user-info",
            "@players",
            "This hint is displayed when the player starts typing the /librelogin user info command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_USER_MIGRATE = new ConfigurationKey<>(
            "autocomplete.user-migrate",
            "@players newName",
            "This hint is displayed when the player starts typing the /librelogin user migrate command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_USER_UNREGISTER = new ConfigurationKey<>(
            "autocomplete.user-unregister",
            "@players",
            "This hint is displayed when the player starts typing the /librelogin user unregister command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_USER_DELETE = new ConfigurationKey<>(
            "autocomplete.user-delete",
            "@players",
            "This hint is displayed when the player starts typing the /librelogin user delete command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_USER_PREMIUM = new ConfigurationKey<>(
            "autocomplete.user-premium",
            "@players",
            "This hint is displayed when the player starts typing the /librelogin user premium command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_USER_CRACKED = new ConfigurationKey<>(
            "autocomplete.user-cracked",
            "@players",
            "This hint is displayed when the player starts typing the /librelogin user cracked command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_USER_REGISTER = new ConfigurationKey<>(
            "autocomplete.user-register",
            "@players password",
            "This hint is displayed when the player starts typing the /librelogin user register command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_USER_LOGIN = new ConfigurationKey<>(
            "autocomplete.user-login",
            "@players",
            "This hint is displayed when the player starts typing the /librelogin user login command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_USER_2FA_OFF = new ConfigurationKey<>(
            "autocomplete.user-2fa-off",
            "@players",
            "This hint is displayed when the player starts typing the /librelogin user 2fa-off command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_USER_EMAIL_OFF = new ConfigurationKey<>(
            "autocomplete.user-email-off",
            "@players",
            "This hint is displayed when the player starts typing the /librelogin user emailoff command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_USER_SET_EMAIL = new ConfigurationKey<>(
            "autocomplete.user-set-email",
            "@players email",
            "This hint is displayed when the player starts typing the /librelogin user setemail command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_USER_ALTS = new ConfigurationKey<>(
            "autocomplete.user-alts",
            "@players",
            "This hint is displayed when the player starts typing the /librelogin user alts command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_USER_CHANGE_PASSWORD = new ConfigurationKey<>(
            "autocomplete.user-pass-change",
            "@players newPassword",
            "This hint is displayed when the player starts typing the /librelogin user pass-change command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_2FA_CONFIRM = new ConfigurationKey<>(
            "autocomplete.2fa-confirm",
            "code",
            "This hint is displayed when the player starts typing the /2fa-confirm command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_CHANGE_PASSWORD = new ConfigurationKey<>(
            "autocomplete.change-password",
            "oldPassword newPassword",
            "This hint is displayed when the player starts typing the /changepassword command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_EMAIL_TEST = new ConfigurationKey<>(
            "autocomplete.email-test",
            "address",
            "This hint is displayed when the player starts typing the /librelogin email test command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_SET_EMAIL = new ConfigurationKey<>(
            "autocomplete.set-email",
            "address password",
            "This hint is displayed when the player starts typing the /setemail command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_VERIFY_EMAIL = new ConfigurationKey<>(
            "autocomplete.verify-email",
            "code",
            "This hint is displayed when the player starts typing the /verifyemail command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_RESET_PASSWORD = new ConfigurationKey<>(
            "autocomplete.reset-password",
            "",
            "This hint is displayed when the player starts typing the /resetpassword command.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> AUTOCOMPLETE_CONFIRM_PASSWORD_RESET = new ConfigurationKey<>(
            "autocomplete.confirm-password-reset",
            "code newPassword newPassword",
            "This hint is displayed when the player starts typing the /confirmpasswordreset command.",
            ConfigurateHelper::getString
    );

    /*
    FancyDialogs Integration Messages
     */

    public static final ConfigurationKey<String> DIALOG_LOGIN_TITLE = new ConfigurationKey<>(
            "dialog.login.title",
            "<gradient:#00ff87:#60efff>登录</gradient>",
            "The title of the login dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_LOGIN_BODY = new ConfigurationKey<>(
            "dialog.login.body",
            "<white>欢迎回来！请输入您的密码以继续游戏。</white>",
            "The body text of the login dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_LOGIN_PASSWORD_LABEL = new ConfigurationKey<>(
            "dialog.login.password-label",
            "<yellow>密码</yellow>",
            "The label for the password field in login dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_LOGIN_2FA_LABEL = new ConfigurationKey<>(
            "dialog.login.2fa-label",
            "<yellow>双因素验证码</yellow>",
            "The label for the 2FA code field in login dialog (only shown when 2FA is enabled).",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_REGISTER_TITLE = new ConfigurationKey<>(
            "dialog.register.title",
            "<gradient:#ff6b6b:#feca57>注册账户</gradient>",
            "The title of the register dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_REGISTER_BODY = new ConfigurationKey<>(
            "dialog.register.body",
            "<white>欢迎来到我们的服务器！请设置一个密码来保护您的账户。</white>",
            "The body text of the register dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_REGISTER_PASSWORD_LABEL = new ConfigurationKey<>(
            "dialog.register.password-label",
            "<yellow>设置密码</yellow>",
            "The label for the password field in register dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_REGISTER_CONFIRM_LABEL = new ConfigurationKey<>(
            "dialog.register.confirm-label",
            "<yellow>确认密码</yellow>",
            "The label for the password confirmation field in register dialog.",
            ConfigurateHelper::getString
    );

    // Register Confirmation Dialog Messages
    public static final ConfigurationKey<String> DIALOG_REGISTER_CONFIRMATION_TITLE = new ConfigurationKey<>(
            "dialog.register-confirmation.title",
            "<gradient:#ff6b6b:#feca57>⚠ 注册确认</gradient>",
            "The title of the register confirmation dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_REGISTER_CONFIRMATION_BODY = new ConfigurationKey<>(
            "dialog.register-confirmation.body",
            """
                    <red>⚠ 重要提醒 ⚠</red>
                    
                    <white>您即将在<bold>不绑定邮箱</bold>的情况下注册账户。</white>
                    
                    <yellow>这意味着：</yellow>
                    <gray>• 如果您忘记密码，将<red>无法找回</red></gray>
                    <gray>• 账户安全性会<yellow>大大降低</yellow></gray>
                    
                    <aqua>建议您选择邮箱注册以保护账户安全！</aqua>
                    """,
            "The body text of the register confirmation dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_PASSWORD_RESET_TITLE = new ConfigurationKey<>(
            "dialog.password-reset.title",
            "<gradient:#fa8231:#f5cd79>重置密码</gradient>",
            "The title of the password reset dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_PASSWORD_RESET_BODY = new ConfigurationKey<>(
            "dialog.password-reset.body",
            "<white>请输入您收到的重置代码和新密码。</white>",
            "The body text of the password reset dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_PASSWORD_RESET_TOKEN_LABEL = new ConfigurationKey<>(
            "dialog.password-reset.token-label",
            "<yellow>重置代码</yellow>",
            "The label for the reset token field in password reset dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_PASSWORD_RESET_PASSWORD_LABEL = new ConfigurationKey<>(
            "dialog.password-reset.password-label",
            "<yellow>新密码</yellow>",
            "The label for the new password field in password reset dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_PASSWORD_RESET_CONFIRM_LABEL = new ConfigurationKey<>(
            "dialog.password-reset.confirm-label",
            "<yellow>确认新密码</yellow>",
            "The label for the password confirmation field in password reset dialog.",
            ConfigurateHelper::getString
    );

    // Email Status Dialog Messages
    public static final ConfigurationKey<String> DIALOG_EMAIL_STATUS_TITLE = new ConfigurationKey<>(
            "dialog.email-status.title",
            "<gradient:#ff6b6b:#feca57>找回密码</gradient>",
            "The title of the email status dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_EMAIL_STATUS_BODY_HAS_EMAIL = new ConfigurationKey<>(
            "dialog.email-status.body-has-email",
            """
                    <white>您的账户已绑定邮箱：</white>
                    
                    <aqua><bold>%email%</bold></aqua>
                    
                    <white>我们将向此邮箱发送密码重置验证码。
                    请确保您可以访问此邮箱。</white>
                    """,
            "The body text shown when user has email bound. Use %email% placeholder for masked email.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_EMAIL_STATUS_BODY_NO_EMAIL = new ConfigurationKey<>(
            "dialog.email-status.body-no-email",
            """
                    <red><bold>⚠ 账户未绑定邮箱 ⚠</bold></red>
                    
                    <white>您的账户没有绑定邮箱，无法通过邮箱找回密码。</white>
                    
                    <yellow>请联系服务器管理员协助找回密码，或重新注册账户。</yellow>
                    """,
            "The body text shown when user has no email bound.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_LOGIN = new ConfigurationKey<>(
            "dialog.button.login",
            "<green>登录</green>",
            "The text of the login button.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_REGISTER = new ConfigurationKey<>(
            "dialog.button.register",
            "<green>注册</green>",
            "The text of the register button.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_RESET_PASSWORD = new ConfigurationKey<>(
            "dialog.button.reset-password",
            "<aqua>重置密码</aqua>",
            "The text of the reset password button.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_FORGOT_PASSWORD = new ConfigurationKey<>(
            "dialog.button.forgot-password",
            "<yellow>忘记密码？</yellow>",
            "The text of the forgot password button in login dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_BACK_TO_LOGIN = new ConfigurationKey<>(
            "dialog.button.back-to-login",
            "<gray>返回登录</gray>",
            "The text of the back to login button.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_CONTINUE_RESET = new ConfigurationKey<>(
            "dialog.button.continue-reset",
            "<aqua>继续找回密码</aqua>",
            "The text of the continue password reset button in email status dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_FANCYDIALOGS_VERSION = new ConfigurationKey<>(
            "error-fancydialogs-version",
            "<red>FancyDialogs requires Paper 1.21.6 or higher. Falling back to command-based login.</red>",
            "This message is logged when FancyDialogs is enabled but the server version is too old.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_FANCYDIALOGS_NOT_INSTALLED = new ConfigurationKey<>(
            "error-fancydialogs-not-installed",
            "<yellow>FancyDialogs is not installed. Falling back to command-based login.</yellow>",
            "This message is logged when FancyDialogs is enabled in config but the plugin is not installed.",
            ConfigurateHelper::getString
    );

    // 2FA Setup Dialog Messages
    public static final ConfigurationKey<String> DIALOG_2FA_SETUP_TITLE = new ConfigurationKey<>(
            "dialog.2fa-setup.title",
            "<gold><b>设置双因素验证</b></gold>",
            "The title of the 2FA setup dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_2FA_SETUP_BODY = new ConfigurationKey<>(
            "dialog.2fa-setup.body",
            """
                    <white>请使用您的身份验证器应用（如 Google Authenticator）
                    扫描下方的二维码或手动输入密钥。
                    
                    扫描后，输入6位验证码以完成设置。</white>
                    
                    <gray>密钥: <yellow>%secret%</yellow></gray>
                    """,
            "The body text of the 2FA setup dialog. Use %secret% placeholder for the TOTP secret.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_2FA_SETUP_CODE_LABEL = new ConfigurationKey<>(
            "dialog.2fa-setup.code-label",
            "<yellow>验证码</yellow>",
            "The label for the verification code field in 2FA setup dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_CONFIRM_2FA = new ConfigurationKey<>(
            "dialog.button.confirm-2fa",
            "<green>确认</green>",
            "The text of the confirm button in 2FA setup dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_SKIP_2FA = new ConfigurationKey<>(
            "dialog.button.skip-2fa",
            "<gray>跳过</gray>",
            "The text of the skip button in 2FA setup dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_DISCONNECT = new ConfigurationKey<>(
            "dialog.button.disconnect",
            "<red>断开连接</red>",
            "The text of the disconnect button in login/register dialogs.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_2FA_VERIFY_FAILED = new ConfigurationKey<>(
            "error-2fa-verify-failed",
            "<red>验证码错误，请重试！</red>",
            "This message is shown when the 2FA verification code is incorrect.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_2FA_ADMIN_CANNOT_SKIP = new ConfigurationKey<>(
            "error-2fa-admin-cannot-skip",
            "<red>管理员必须设置双因素验证！</red>",
            "This message is shown when an admin tries to skip 2FA setup.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> SUCCESS_2FA_SETUP = new ConfigurationKey<>(
            "success-2fa-setup",
            "<green>双因素验证设置成功！</green>",
            "This message is shown when 2FA is successfully set up.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_2FA_SETUP_REQUIRED = new ConfigurationKey<>(
            "info-2fa-setup-required",
            "<yellow>您需要设置双因素验证才能继续。</yellow>",
            "This message is shown to inform the player that 2FA setup is required.",
            ConfigurateHelper::getString
    );

    // Announcement Dialog Messages
    public static final ConfigurationKey<String> DIALOG_ANNOUNCEMENT_TITLE = new ConfigurationKey<>(
            "dialog.announcement.title",
            "<gradient:gold:yellow><b>服务器公告</b></gradient>",
            "The title of the announcement dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_ANNOUNCEMENT_BODY = new ConfigurationKey<>(
            "dialog.announcement.body",
            "%content%",
            "The body text of the announcement dialog. The %content% placeholder will be replaced with the announcement content from the config.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_CONFIRM_ANNOUNCEMENT = new ConfigurationKey<>(
            "dialog.button.confirm-announcement",
            "<green>我已阅读</green>",
            "The text of the confirm button in announcement dialog.",
            ConfigurateHelper::getString
    );

    // Common error messages for dialogs
    public static final ConfigurationKey<String> ERROR_EMPTY_INPUT = new ConfigurationKey<>(
            "error-empty-input",
            "请输入内容后提交！",
            "This message is shown when required input fields are empty.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_USER_DATA = new ConfigurationKey<>(
            "error-user-data",
            "用户数据错误！",
            "This message is shown when user data is corrupted or missing.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_FILL_ALL_FIELDS = new ConfigurationKey<>(
            "error-fill-all-fields",
            "请填写所有必需字段！",
            "This message is shown when not all required fields are filled.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_LOGIN_FAILED = new ConfigurationKey<>(
            "error-login-failed",
            "用户名或密码错误，请重试！",
            "This message is shown when login fails (password or 2FA incorrect). For security reasons, it doesn't specify which field is wrong.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_AUTHORIZATION_FAILED = new ConfigurationKey<>(
            "error-authorization-failed",
            "授权失败，请重试或联系管理员！",
            "This message is shown when player authorization fails after successful login.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_PASSWORD_RESET_MISSING_FIELDS = new ConfigurationKey<>(
            "error-password-reset-missing-fields",
            "请填写所有字段（重置代码、新密码、确认密码）！",
            "This message is shown when not all password reset fields are filled.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_REGISTER_MISSING_FIELDS = new ConfigurationKey<>(
            "error-register-missing-fields",
            "请填写密码和确认密码！",
            "This message is shown when password fields are not filled during registration.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_2FA_MISSING_CODE = new ConfigurationKey<>(
            "error-2fa-missing-code",
            "请输入验证码！",
            "This message is shown when 2FA verification code is not provided.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_2FA_NOT_AVAILABLE = new ConfigurationKey<>(
            "error-2fa-not-available",
            "双因素验证功能不可用！",
            "This message is shown when 2FA system is not available.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_2FA_RESCAN_FAILED = new ConfigurationKey<>(
            "error-2fa-rescan-failed",
            "重新生成二维码失败，请重试！",
            "This message is shown when 2FA QR code rescan fails.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_2FA_SETUP_FAILED = new ConfigurationKey<>(
            "error-2fa-setup-failed",
            "双因素验证设置失败，请重试或联系管理员！",
            "This message is shown when 2FA setup process fails.",
            ConfigurateHelper::getString
    );

    /*
    Email Registration Messages
     */

    // Email Register Dialog Messages
    public static final ConfigurationKey<String> DIALOG_EMAIL_REGISTER_TITLE = new ConfigurationKey<>(
            "dialog.email-register.title",
            "<gradient:#4fc3f7:#29b6f6>邮箱注册</gradient>",
            "The title of the email register dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_EMAIL_REGISTER_BODY = new ConfigurationKey<>(
            "dialog.email-register.body",
            "<white>请设置您的账户密码并绑定邮箱地址。\n邮箱将用于验证您的身份和找回密码。</white>",
            "The body text of the email register dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_EMAIL_REGISTER_PASSWORD_LABEL = new ConfigurationKey<>(
            "dialog.email-register.password-label",
            "<yellow>设置密码</yellow>",
            "The label for the password field in email register dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_EMAIL_REGISTER_CONFIRM_LABEL = new ConfigurationKey<>(
            "dialog.email-register.confirm-label",
            "<yellow>确认密码</yellow>",
            "The label for the password confirmation field in email register dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_EMAIL_REGISTER_EMAIL_LABEL = new ConfigurationKey<>(
            "dialog.email-register.email-label",
            "<yellow>邮箱地址</yellow>",
            "The label for the email field in email register dialog.",
            ConfigurateHelper::getString
    );

    // Email Verification Dialog Messages
    public static final ConfigurationKey<String> DIALOG_EMAIL_VERIFICATION_TITLE = new ConfigurationKey<>(
            "dialog.email-verification.title",
            "<gradient:#66bb6a:#43a047>邮箱验证</gradient>",
            "The title of the email verification dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_EMAIL_VERIFICATION_BODY = new ConfigurationKey<>(
            "dialog.email-verification.body",
            """
                    <white>验证邮件已发送到：<aqua>%email%</aqua>
                    
                    请查看您的邮箱并输入收到的验证码。
                    如果没有收到邮件，请检查垃圾邮件文件夹。</white>
                    
                    <gray>验证码将在 %timeout% 分钟后过期。</gray>
                    """,
            "The body text of the email verification dialog. Use %email% and %timeout% placeholders.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_EMAIL_VERIFICATION_CODE_LABEL = new ConfigurationKey<>(
            "dialog.email-verification.code-label",
            "<yellow>验证码</yellow>",
            "The label for the verification code field in email verification dialog.",
            ConfigurateHelper::getString
    );

    // Email Input Dialog Messages (simplified email registration)
    public static final ConfigurationKey<String> DIALOG_EMAIL_INPUT_TITLE = new ConfigurationKey<>(
            "dialog.email-input.title",
            "<gradient:#4fc3f7:#29b6f6>邮箱绑定</gradient>",
            "The title of the email input dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_EMAIL_INPUT_BODY = new ConfigurationKey<>(
            "dialog.email-input.body",
            "<white>请输入您的邮箱地址以完成注册。\n邮箱将用于验证您的身份和找回密码。</white>",
            "The body text of the email input dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_EMAIL_INPUT_EMAIL_LABEL = new ConfigurationKey<>(
            "dialog.email-input.email-label",
            "<yellow>邮箱地址</yellow>",
            "The label for the email field in email input dialog.",
            ConfigurateHelper::getString
    );

    // Email Register Buttons
    public static final ConfigurationKey<String> DIALOG_BUTTON_EMAIL_REGISTER = new ConfigurationKey<>(
            "dialog.button.email-register",
            "<aqua>邮箱注册</aqua>",
            "The text of the email register button in register dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_EMAIL_SUBMIT = new ConfigurationKey<>(
            "dialog.button.email-submit",
            "<green>提交注册</green>",
            "The text of the submit button in email register dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_VERIFY_EMAIL = new ConfigurationKey<>(
            "dialog.button.verify-email",
            "<green>验证邮箱</green>",
            "The text of the verify button in email verification dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_BACK_TO_REGISTER = new ConfigurationKey<>(
            "dialog.button.back-to-register",
            "<gray>返回注册</gray>",
            "The text of the back to register button.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_CONFIRM_CONTINUE = new ConfigurationKey<>(
            "dialog.button.confirm-continue",
            "<red>确认继续注册</red>",
            "The text of the confirm continue button in register confirmation dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_GO_EMAIL_REGISTER = new ConfigurationKey<>(
            "dialog.button.go-email-register",
            "<green>进入邮箱注册</green>",
            "The text of the go to email register button in register confirmation dialog.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> DIALOG_BUTTON_RESEND_EMAIL = new ConfigurationKey<>(
            "dialog.button.resend-email",
            "<yellow>重新发送邮件</yellow>",
            "The text of the resend email button in email verification dialog.",
            ConfigurateHelper::getString
    );

    // Email Registration Error Messages
    public static final ConfigurationKey<String> ERROR_EMAIL_INVALID_FORMAT = new ConfigurationKey<>(
            "error-email-invalid-format",
            "邮箱格式不正确，请输入有效的邮箱地址！",
            "This message is shown when the email format is invalid.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_EMAIL_DOMAIN_BLOCKED = new ConfigurationKey<>(
            "error-email-domain-blocked",
            "此邮箱域名不被允许，请使用其他邮箱！",
            "This message is shown when the email domain is in the blacklist.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_EMAIL_DOMAIN_NOT_ALLOWED = new ConfigurationKey<>(
            "error-email-domain-not-allowed",
            "此邮箱域名不在允许列表中，请使用允许的邮箱！",
            "This message is shown when the email domain is not in the whitelist.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_EMAIL_ALREADY_USED = new ConfigurationKey<>(
            "error-email-already-used",
            "此邮箱已被其他账户使用，请使用其他邮箱！",
            "This message is shown when the email is already registered by another account.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_EMAIL_VERIFICATION_TIMEOUT = new ConfigurationKey<>(
            "error-email-verification-timeout",
            "邮箱验证已超时，请重新注册！",
            "This message is shown when email verification code has expired.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_EMAIL_VERIFICATION_INVALID = new ConfigurationKey<>(
            "error-email-verification-invalid",
            "验证码错误或已失效，请检查后重试！",
            "This message is shown when email verification code is incorrect or expired.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_EMAIL_REGISTER_DISABLED = new ConfigurationKey<>(
            "error-email-register-disabled",
            "邮箱注册功能未启用！",
            "This message is shown when email registration is disabled in config.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_EMAIL_REGISTER_RATE_LIMITED = new ConfigurationKey<>(
            "error-email-register-rate-limited",
            "邮箱注册请求过于频繁，请稍后再试！",
            "This message is shown when email registration is rate limited.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_EMAIL_REGISTER_RATE_LIMIT_IP = new ConfigurationKey<>(
            "error-email-register-rate-limit-ip",
            "您的IP地址邮箱注册请求过于频繁，请等待 %minutes% 分钟后再试！",
            "This message is shown when email registration is rate limited by IP address. %minutes% is the remaining time.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_EMAIL_REGISTER_RATE_LIMIT_PLAYER = new ConfigurationKey<>(
            "error-email-register-rate-limit-player",
            "您的账户邮箱注册请求过于频繁，请等待 %minutes% 分钟后再试！",
            "This message is shown when email registration is rate limited by player UUID. %minutes% is the remaining time.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_EMAIL_REGISTER_RATE_LIMIT_EMAIL = new ConfigurationKey<>(
            "error-email-register-rate-limit-email",
            "此邮箱地址注册请求过于频繁，请等待 %minutes% 分钟后再试！",
            "This message is shown when email registration is rate limited by email address. %minutes% is the remaining time.",
            ConfigurateHelper::getString
    );


    public static final ConfigurationKey<String> ERROR_EMAIL_MISSING_FIELDS = new ConfigurationKey<>(
            "error-email-missing-fields",
            "请填写所有必需字段（密码、确认密码、邮箱）！",
            "This message is shown when required email registration fields are missing.",
            ConfigurateHelper::getString
    );

    // Email Template Management Messages
    public static final ConfigurationKey<String> INFO_EMAIL_TEMPLATES_RELOADED = new ConfigurationKey<>(
            "info-email-templates-reloaded",
            "邮件模板已成功重新加载！",
            "This message is shown when email templates are successfully reloaded.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_EMAIL_TEMPLATES_FORCE_RELEASED = new ConfigurationKey<>(
            "info-email-templates-force-released",
            "邮件模板已强制重新释放到插件目录！",
            "This message is shown when email templates are force released to the plugin directory.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_EMAIL_TEMPLATES_PATH = new ConfigurationKey<>(
            "info-email-templates-path",
            "模板路径：%path%",
            "This message shows the path to email templates directory.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_EMAIL_NOT_ENABLED = new ConfigurationKey<>(
            "error-email-not-enabled",
            "邮件功能未启用！",
            "This message is shown when trying to reload email templates but email is not enabled.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_EMAIL_HANDLER_NOT_SUPPORTED = new ConfigurationKey<>(
            "error-email-handler-not-supported",
            "当前邮件处理器不支持模板重新加载！",
            "This message is shown when the email handler doesn't support template reloading.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> ERROR_EMAIL_TEMPLATES_RELOAD_FAILED = new ConfigurationKey<>(
            "error-email-templates-reload-failed",
            "邮件模板重新加载失败！请查看控制台了解详情。",
            "This message is shown when email template reloading fails.",
            ConfigurateHelper::getString
    );

    // Email Registration Success Messages
    public static final ConfigurationKey<String> INFO_EMAIL_REGISTER_SENT = new ConfigurationKey<>(
            "info-email-register-sent",
            "注册信息已提交，验证邮件已发送到您的邮箱！",
            "This message is shown when email registration is submitted successfully.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_EMAIL_VERIFICATION_SUCCESS = new ConfigurationKey<>(
            "info-email-verification-success",
            "邮箱验证成功！账户注册完成，正在登录...",
            "This message is shown when email verification is completed successfully.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> INFO_EMAIL_RESENT = new ConfigurationKey<>(
            "info-email-resent",
            "验证邮件已重新发送，请查收！",
            "This message is shown when verification email is resent successfully.",
            ConfigurateHelper::getString
    );

    // Email Content Templates
    public static final ConfigurationKey<String> EMAIL_REGISTER_VERIFICATION_SUBJECT = new ConfigurationKey<>(
            "email-register-verification-subject",
            "验证您在 %server% 的注册",
            "This is the subject of the registration verification email.",
            ConfigurateHelper::getString
    );

    public static final ConfigurationKey<String> EMAIL_REGISTER_VERIFICATION_CONTENT = new ConfigurationKey<>(
            "email-register-verification-content",
            """
                    您好 %name%！<br>
                    欢迎注册 %server%！<br>
                    <br>
                    为了完成账户注册，请在游戏中输入以下验证码：<br>
                    <b><code><h1>%code%</h1></code></b><br>
                    <br>
                    此验证码将在 %timeout% 分钟后失效。<br>
                    如果您没有请求此注册，请忽略此邮件。<br>
                    """,
            "This email is sent to the player for registration verification. You can insert any HTML code into this message.",
            ConfigurateHelper::getString
    );

}
